# Generated by Django 5.2.7 on 2025-10-07 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_categories", models.JSONField(default=list)),
                ("preferred_language", models.CharField(default="en", max_length=10)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("email_notifications", models.BooleanField(default=True)),
                ("show_images", models.BooleanField(default=True)),
                ("dark_mode", models.BooleanField(default=False)),
                ("total_articles_read", models.IntegerField(default=0)),
                ("total_upvotes", models.IntegerField(default=0)),
                ("total_downvotes", models.IntegerField(default=0)),
                ("total_comments", models.IntegerField(default=0)),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("avatar", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("onboarding_complete", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
